version: '3.8'
services:
  # mysql:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: slimframe
  #     MYSQL_USER: slimframe
  #     MYSQL_PASSWORD: slimframe
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20

  php:
    build:
      context: ./docker/php
    restart: always
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: slimframe
      DB_USER: slimframe
      DB_PASSWORD: slimframe
      DB_CHARSET: utf8mb4
    volumes:
      - ./.:/var/www/html

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php

volumes:
  mysql_data:
